rules:
  - id: empty-catch
    languages:
      - kotlin
    message: Found Empty Catch Block
    pattern: |
      try {
        ...
      } catch (e : Exception) {
        ...
        throw ...
      }
    severity: LOW
