title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
paths = [
    "..lock",
    "node_modules/.",
    "(.*/)?test(s)?/.fixture.",
    ".env.example$",
]
