name: DAST

on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and build
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and run app
        run: |
          chmod +x gradlew
          ./gradlew build -x test
          ./gradlew run &
          sleep 20

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'http://localhost:8080'
          fail_action: false
          artifact_name: zap-scan-reports
